"""adding last_name to person table

Revision ID: 51a002701004
Revises: d1ac27b37ba4
Create Date: 2025-02-01 23:13:39.239156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a002701004'
down_revision: Union[str, None] = 'd1ac27b37ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'last_name')
    # ### end Alembic commands ###
